version: "3.7"

services:
  mongo:
    image: mongo
    restart: unless-stopped
    env_file:
      - ./.envs/.mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    env_file:
      - ./.envs/.mongo-express
    depends_on:
      - mongo

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    container_name: redis-finpy
    volumes:
      - redis_data:/data

volumes:
    mongodb_data:
    redis_data:
